# Generated by Django 2.2.19 on 2022-01-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
